# Generated by Django 5.0.7 on 2024-07-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', 'Узбекский'), ('ru', 'Русский')], default='ru', max_length=255),
        ),
    ]
