# Generated by Django 5.0.7 on 2024-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfer_level',
            field=models.IntegerField(default=0, verbose_name='Уровень лимита трансфера'),
        ),
        migrations.AddField(
            model_name='user',
            name='transfer_limit',
            field=models.IntegerField(default=0, verbose_name='Дневной лимит трансфера'),
        ),
    ]
