# Generated by Django 5.0.7 on 2024-07-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_transfer_level_user_transfer_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transfer_level',
            field=models.IntegerField(default=1, verbose_name='Уровень лимита трансфера'),
        ),
    ]
