version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  bot:
    build: .
    command: python3 -m bot polling
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: xspin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: omonullo66
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
