# Generated by Django 5.0.7 on 2024-07-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено время')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
                ('promocode', models.CharField(max_length=255, verbose_name='Промо-код')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('max_users', models.IntegerField(verbose_name='Максимальное количество пользователей')),
            ],
            options={
                'verbose_name': 'Промо-код',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
