# Generated by Django 5.0.7 on 2024-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0002_usedpromocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='promocode',
            field=models.CharField(max_length=255, unique=True, verbose_name='Промо-код'),
        ),
    ]
