# Generated by Django 5.0.7 on 2024-07-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_alter_group_invite_link_alter_group_username'),
        ('users', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено время')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Чат')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_transfers', to='users.user', verbose_name='Пользователю')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transfers', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Трансфер',
                'verbose_name_plural': 'Трансферы',
            },
        ),
        migrations.CreateModel(
            name='TransferAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено время')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
                ('transfer_type', models.CharField(choices=[('increase', 'Увеличивать'), ('decrease', 'Снижаться')], max_length=255, verbose_name='Тип трансфера')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin', verbose_name='Админ')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Чат')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователю')),
            ],
            options={
                'verbose_name': 'Трансфер (Админ)',
                'verbose_name_plural': 'Трансферы (Админ)',
            },
        ),
    ]
