# Generated by Django 5.0.7 on 2024-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferadmin',
            name='transfer_type',
            field=models.CharField(choices=[('increase', 'Увеличивать (+)'), ('decrease', 'Снижаться (-)')], max_length=255, verbose_name='Тип трансфера'),
        ),
    ]
