from db.repositories.base import BaseRepository
from db.repositories.users import UsersTableRepository, AdminsTableRepository
from db.repositories.groups import GroupsTableRepository
from db.repositories.games import GamesHistoryTableRepository
from db.repositories.transfers import TransfersTableRepository
from db.repositories.referalls import ReferallsTableRepository
from db.repositories.promocodes import PromocodesTableRepository, UsedPromocodesTableRepository