# Generated by Django 5.0.7 on 2024-07-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено время')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
                ('chat_id', models.BigIntegerField(verbose_name='ID чата')),
                ('invite_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для приглашения в чат')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Ссылка на чат')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя чата')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
