# Generated by Django 5.0.7 on 2024-07-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
