# Generated by Django 5.0.7 on 2024-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invite_link',
            field=models.URLField(null=True, unique=True, verbose_name='Ссылка для приглашения в чат'),
        ),
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Ссылка на чат'),
        ),
    ]
