# Generated by Django 5.0.7 on 2024-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='is_won',
            field=models.BooleanField(default=True, verbose_name='Выиграл'),
            preserve_default=False,
        ),
    ]
