# Generated by Django 5.0.7 on 2024-07-25 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamehistory_is_won'),
        ('groups', '0003_alter_group_invite_link_alter_group_username'),
        ('users', '0005_user_transfer_level_user_transfer_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь'),
        ),
    ]
